slider_mappings:
    browsers:
        volume: 1
        muted: false
        targets:
            - firefox.exe
            - chrome.exe
    chat:
        volume: 1
        muted: false
        targets:
            - discord.exe
            - signal.exe
    games:
        volume: 0.23000003
        muted: false
        targets:
            - steam.exe
            - pathofexile_x64.exe
            - rocketleague.exe
            - ryujinx.exe
    main:
        volume: 0.7000003
        muted: false
        targets:
            - master
    music:
        volume: 0.75000024
        muted: true
        targets:
            - spotify.exe
invert_sliders: false
connection_info:
    serial_port: COM10
    baud_rate: 115200
noise_reduction_level: default
config_save_interval: 60